cc_library(
    name = "cl_buffer",
    hdrs = ["cl_buffer.h"],
    srcs = ["cl_buffer.cc"],
    copts = [
        "--std=c++1z",
    ],
    visibility = ["//math"],
    deps = [
        "//clutil:util",
    ],
)
